# Generated by Django 5.2.6 on 2025-10-24 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
                ('fecha_nac', models.DateField()),
                ('especialidad', models.CharField(choices=[('cardiologia', 'Cardiología'), ('pediatria', 'Pediatría'), ('traumatologia', 'Traumatología'), ('neurologia', 'Neurología'), ('oftalmologia', 'Oftalmología'), ('odontologia', 'Odontología'), ('medicina_general', 'Medicina General'), ('dermatologia', 'Dermatología')], max_length=50)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('notas', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestor.doctor')),
            ],
        ),
    ]
