# Generated by Django 5.2.6 on 2025-12-17 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0003_usuario_debe_cambiar_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receta',
            old_name='indicaciones_extra',
            new_name='indicaciones',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='tratamiento',
        ),
    ]
