# Generated by Django 5.2.6 on 2025-12-18 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0005_alter_usuario_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='activa',
            field=models.BooleanField(default=True),
        ),
    ]
