# Generated by Django 5.2.6 on 2025-12-18 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0006_receta_activa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tratamiento',
        ),
    ]
